# Generated by Django 3.2 on 2023-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221231_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='7a4a8bf0-2417-422f-9d01-f9b48d30636a', editable=False, max_length=40),
        ),
    ]
