# Generated by Django 3.2 on 2023-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230109_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='858cdff9-4789-4dc5-9074-1ee5ab6a5114', editable=False, max_length=40),
        ),
    ]
