# Generated by Django 3.2 on 2023-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='053596b0-5507-4a0d-864d-987d70a76edd', editable=False, max_length=40),
        ),
    ]
