# Generated by Django 3.2 on 2023-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='c73fe0ef-111f-4bf9-8fcf-d52514c42a1d', editable=False, max_length=40),
        ),
    ]
