# Generated by Django 3.2 on 2023-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='baf1b888-8288-4d0b-8743-6aac87d3dc12', editable=False, max_length=40),
        ),
    ]
