# Generated by Django 3.2 on 2023-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='fdb815de-0ef5-42f9-91a6-81129c5bad2b', editable=False, max_length=40),
        ),
    ]
