# Generated by Django 3.2 on 2023-01-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='c55f4bd7-ef79-42e6-b7c7-87c8a4123686', editable=False, max_length=40),
        ),
    ]
