# Generated by Django 3.2 on 2023-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='04597e29-5995-49eb-b034-bae1bd5012ab', editable=False, max_length=40),
        ),
    ]
