# Generated by Django 3.2 on 2023-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='04615eb9-7e6d-4b85-bcbe-f5b943269ea2', editable=False, max_length=40),
        ),
    ]
