# Generated by Django 3.2 on 2023-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='3b473c18-d850-4f9e-822f-652f5a94ebbe', editable=False, max_length=40),
        ),
    ]
