# Generated by Django 3.2 on 2023-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='0bcba083-ca15-4682-b066-aa7d47fa75dc', editable=False, max_length=40),
        ),
    ]
