# Generated by Django 3.2 on 2023-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='464eecb6-e4af-44e9-8d4c-c6a66d0f4662', editable=False, max_length=40),
        ),
    ]
