# Generated by Django 3.2 on 2023-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='11523874-4202-4f5a-baf9-b992aae9f7f6', editable=False, max_length=40),
        ),
    ]
