# Generated by Django 3.2 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='59b72135-3ff9-44e8-97c0-cfa6b6828ed5', editable=False, max_length=40),
        ),
    ]
