# Generated by Django 3.2 on 2023-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='2f1c393f-2f9e-4622-83df-90594931cd86', editable=False, max_length=40),
        ),
    ]
