# Generated by Django 3.2 on 2023-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='a83c65e9-7406-4b26-8f1e-15d662059e27', editable=False, max_length=40),
        ),
    ]
