# Generated by Django 3.2 on 2023-01-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20230116_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='d5ea13e2-f10f-4578-9936-aa1a7f94329c', editable=False, max_length=40),
        ),
    ]
